In [3]:
# from PIL import Image

# # Load the image
# img = Image.open('/kaggle/input/beach-litter-dataset/test_masks/002800.png')

# # Convert the image to RGB mode
# img = img.convert('RGB')

# # Save the image
# img.save('002800_nopalette.png')

In [4]:
# from IPython.display import Image
# Image('/kaggle/working/002800_nopalette.png')

In [5]:
from PIL import Image
im = Image.open("/kaggle/input/beach-litter-dataset/test_masks/002800.png")
px = im.load()
coordinate = x, y = 150, 59
print (im.getpixel(coordinate));

4


In [6]:
from PIL import Image
im = Image.open("/kaggle/input/cityscapes-subset/annotations_test/0016E5_07959.png")
px = im.load()
coordinate = x, y = 150, 59
print (im.getpixel(coordinate));

1


In [7]:
from PIL import Image
im = Image.open("/kaggle/input/beach-litter-dataset/test_images/002800.jpg")
px = im.load()
coordinate = x, y = 150, 59
print (im.getpixel(coordinate));

(179, 201, 224)


In [8]:
from PIL import Image
im = Image.open("/kaggle/input/cityscapes-subset/images_test/0016E5_07959.png")
px = im.load()
coordinate = x, y = 150, 59
print (im.getpixel(coordinate));

(118, 128, 143)


In [9]:
import cv2
import numpy as np
from PIL import Image

# Existing palette as nested list
# palette = [
#     [80, 0, 0],
#     [0, 80, 0],
#     [80, 80, 0],
#     [0, 0, 80],
#     [80, 0, 80],
#     [0, 80, 80],
#     [80, 80, 80],
#     [40, 0, 0]
# ]

palette = [
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0]
]

img = cv2.imread('/kaggle/input/beach-litter-dataset/test_masks/002800.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
h, w = img.shape[:2]
print(img)

img_pal = np.zeros((h, w), np.uint8)
for i_p, p in enumerate(palette):
    img_pal[np.all(img == p, axis=2)] = i_p
cv2.imwrite('output.png', img_pal)

img_pil = Image.open('output.png')
print(np.array(img_pil))

[[[  0 128 128]
  [  0 128 128]
  [  0 128 128]
  ...
  [  0 128 128]
  [  0 128 128]
  [  0 128 128]]

 [[  0 128 128]
  [  0 128 128]
  [  0 128 128]
  ...
  [  0 128 128]
  [  0 128 128]
  [  0 128 128]]

 [[  0 128 128]
  [  0 128 128]
  [  0 128 128]
  ...
  [  0 128 128]
  [  0 128 128]
  [  0 128 128]]

 ...

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  ...
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  ...
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  ...
  [128 128 128]
  [128 128 128]
  [128 128 128]]]
[[5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 ...
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]]


In [10]:
img = cv2.imread('/kaggle/input/beach-litter-dataset/test_masks/002800.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# print(np.unique(img))
set( tuple(v) for m2d in img for v in m2d )

{(0, 0, 128), (0, 128, 128), (128, 0, 128), (128, 128, 128)}

In [11]:
img = cv2.imread('/kaggle/input/beach-litter-dataset/test_masks/002857.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# print(np.unique(img))
set( tuple(v) for m2d in img for v in m2d )

{(0, 0, 128),
 (0, 128, 0),
 (0, 128, 128),
 (64, 0, 0),
 (128, 0, 0),
 (128, 0, 128),
 (128, 128, 0),
 (128, 128, 128)}

# Run ini kebawah & tinggal ganti path maskny aja

In [1]:
# https://stackoverflow.com/questions/67967366/how-to-write-image-with-palette-information

import cv2
import numpy as np
from PIL import Image
import os

palette = [
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0]
]
mask_list = os.listdir('/kaggle/input/beach-litter-dataset/train_masks')

folder_path = "/kaggle/working/output_images"
os.makedirs(folder_path, exist_ok = True)

for i in mask_list:
    img_path = os.path.join('/kaggle/input/beach-litter-dataset/train_masks', i)
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    img_pal = np.zeros((h, w), np.uint8)
    for i_p, p in enumerate(palette):
        img_pal[np.all(img == p, axis=2)] = i_p
    output_path = os.path.join(folder_path, i)
    cv2.imwrite(output_path, img_pal)

## run ini buat ngezip folder output_images biar g ush download filenya 1"

In [2]:
import shutil

# # Path to the folder you want to compress
# folder_path = '/kaggle/working/output_images'

# Path where you want to save the compressed file
zip_path = '/kaggle/working/output_images.zip'

# Compress the folder
shutil.make_archive(zip_path.replace('.zip', ''), 'zip', folder_path)

'/kaggle/working/output_images.zip'

In [ ]:
# mask_list